steps:
  # Build AI Agent service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/alpha-orion-repo/ai-agent-service:$COMMIT_SHA', './backend-services/services/ai-agent-service/']

  # Push AI Agent image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/alpha-orion-repo/ai-agent-service:$COMMIT_SHA']

  # Build AI Optimizer service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/alpha-orion-repo/ai-optimizer:$COMMIT_SHA', './backend-services/services/ai-optimizer/']

  # Push AI Optimizer image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/alpha-orion-repo/ai-optimizer:$COMMIT_SHA']

  # Build User API service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/alpha-orion-repo/user-api-service:$COMMIT_SHA', './backend-services/services/user-api-service/']

  # Push User API image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/alpha-orion-repo/user-api-service:$COMMIT_SHA']

  # Build Withdrawal service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/alpha-orion-repo/withdrawal-service:$COMMIT_SHA', './backend-services/services/withdrawal-service/']

  # Push Withdrawal image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/alpha-orion-repo/withdrawal-service:$COMMIT_SHA']

  # Build frontend service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/alpha-orion-repo/frontend:$COMMIT_SHA', './frontend/']

  # Push frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/alpha-orion-repo/frontend:$COMMIT_SHA']

  # Deploy with Terraform
  - name: 'hashicorp/terraform'
    args: ['init']
    dir: 'terraform/'

  - name: 'hashicorp/terraform'
    args: ['plan', '-out=tfplan']
    dir: 'terraform/'

  - name: 'hashicorp/terraform'
    args: ['apply', '-auto-approve', 'tfplan']
    dir: 'terraform/'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Store build artifacts
artifacts:
  objects:
    location: 'gs://alpha-orion-build-artifacts/'
    paths: ['terraform/tfplan']
