options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: 'us-central1'
  _API_URL: ''

steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-frontend'
    dir: '.'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/frontend-dashboard:$COMMIT_SHA', '-f', 'docker/frontend.Dockerfile', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/frontend-dashboard:$COMMIT_SHA']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-frontend'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'frontend-dashboard'
      - '--image'
      - 'gcr.io/$PROJECT_ID/frontend-dashboard:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--port=80'
      - '--set-env-vars=API_BASE_URL=${_API_URL}'

images:
  - 'gcr.io/$PROJECT_ID/frontend-dashboard:$COMMIT_SHA'
