steps:
  # Step 1: Setup environment and authenticate
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'setup-environment'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "ðŸš€ Setting up Alpha-Orion Enterprise Deployment Environment"
        echo "Project: $PROJECT_ID"
        echo "Branch: $BRANCH_NAME"
        echo "Commit: $COMMIT_SHA"

        # Set project
        gcloud config set project $PROJECT_ID

        # Authenticate with enhanced credentials
        echo "ðŸ” Setting up enhanced GCP authentication..."
        gcloud auth activate-service-account --key-file=/secrets/gcp-service-account-key.json

        # Enable required APIs with retry logic
        echo "ðŸ”Œ Enabling required GCP APIs..."
        apis=(
          "compute.googleapis.com"
          "dataflow.googleapis.com"
          "bigtable.googleapis.com"
          "aiplatform.googleapis.com"
          "bigquery.googleapis.com"
          "monitoring.googleapis.com"
          "logging.googleapis.com"
          "pubsub.googleapis.com"
          "secretmanager.googleapis.com"
          "cloudbuild.googleapis.com"
          "containerregistry.googleapis.com"
          "run.googleapis.com"
          "vpcaccess.googleapis.com"
          "servicenetworking.googleapis.com"
          "cloudresourcemanager.googleapis.com"
          "iam.googleapis.com"
          "cloudbilling.googleapis.com"
          "securitycenter.googleapis.com"
          "cloudarmor.googleapis.com"
          "networkconnectivity.googleapis.com"
          "certificatemanager.googleapis.com"
        )

        for api in "${apis[@]}"; do
          echo "Enabling $api..."
          gcloud services enable $api --project=$PROJECT_ID || echo "Warning: Failed to enable $api"
        done

        echo "âœ… Environment setup complete"

  # Step 2: Run deployment diagnostics and fixes
  - name: 'python:3.9'
    id: 'diagnostics-and-fixes'
    entrypoint: 'python3'
    args:
      - 'fix-gcp-deployment-issues.py'
      - '--project=$PROJECT_ID'
      - '--diagnose-only'
    waitFor: ['setup-environment']

  # Step 3: Build and push Docker images
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-frontend'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "ðŸ—ï¸ Building Alpha-Orion Frontend"
        cd frontend

        # Build React application
        npm install
        npm run build

        # Build Docker image
        docker build -t gcr.io/$PROJECT_ID/alpha-orion-frontend:$COMMIT_SHA .
        docker build -t gcr.io/$PROJECT_ID/alpha-orion-frontend:latest .

        # Push images
        docker push gcr.io/$PROJECT_ID/alpha-orion-frontend:$COMMIT_SHA
        docker push gcr.io/$PROJECT_ID/alpha-orion-frontend:latest

        echo "âœ… Frontend image built and pushed"
    waitFor: ['diagnostics-and-fixes']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-backend'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "ðŸ—ï¸ Building Alpha-Orion Backend Services"

        # Build user API service
        cd backend-services/services/user-api-service
        docker build -t gcr.io/$PROJECT_ID/alpha-orion-user-api:$COMMIT_SHA .
        docker build -t gcr.io/$PROJECT_ID/alpha-orion-user-api:latest .
        docker push gcr.io/$PROJECT_ID/alpha-orion-user-api:$COMMIT_SHA
        docker push gcr.io/$PROJECT_ID/alpha-orion-user-api:latest

        # Build AI agent service
        cd ../ai-agent-service
        docker build -t gcr.io/$PROJECT_ID/alpha-orion-ai-agent:$COMMIT_SHA .
        docker build -t gcr.io/$PROJECT_ID/alpha-orion-ai-agent:latest .
        docker push gcr.io/$PROJECT_ID/alpha-orion-ai-agent:$COMMIT_SHA
        docker push gcr.io/$PROJECT_ID/alpha-orion-ai-agent:latest

        # Build brain orchestrator
        cd ../brain-orchestrator
        docker build -t gcr.io/$PROJECT_ID/alpha-orion-brain:$COMMIT_SHA .
        docker build -t gcr.io/$PROJECT_ID/alpha-orion-brain:latest .
        docker push gcr.io/$PROJECT_ID/alpha-orion-brain:$COMMIT_SHA
        docker push gcr.io/$PROJECT_ID/alpha-orion-brain:latest

        echo "âœ… Backend services built and pushed"
    waitFor: ['diagnostics-and-fixes']

  # Step 4: Deploy Terraform infrastructure
  - name: 'hashicorp/terraform:1.5.0'
    id: 'terraform-init'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "ðŸ—ï¸ Initializing Terraform Infrastructure"
        cd infrastructure

        # Initialize Terraform
        terraform init -upgrade

        # Create terraform.tfvars from environment
        cat > terraform.tfvars << EOF
        project_id = "$PROJECT_ID"
        region = "us-central1"
        environment = "production"
        arbitrage_machine_type = "n2-standard-32"
        arbitrage_min_cpu_platform = "Intel Cascade Lake"
        arbitrage_boot_disk_size = 100
        arbitrage_boot_disk_type = "pd-extreme"
        enable_gpu = true
        gpu_type = "nvidia-tesla-t4"
        gpu_count = 2
        bigtable_instance_name = "arbitrage-market-data"
        bigtable_cluster_id = "arbitrage-cluster"
        bigtable_num_nodes = 20
        bigtable_storage_type = "SSD"
        dataflow_machine_type = "n2-highcpu-32"
        dataflow_max_workers = 100
        dataflow_enable_streaming = true
        vertex_ai_region = "us-central1"
        vertex_ai_accelerator_type = "NVIDIA_TESLA_T4"
        vertex_ai_accelerator_count = 2
        enable_global_lb = true
        enable_cdn = true
        ssl_certificate_domains = ["arbitrage.alpha-orion.com"]
        enable_cloud_armor = true
        enable_security_command_center = true
        enable_vpc_service_controls = true
        enable_enterprise_monitoring = true
        monitoring_notification_channels = ["email", "slack", "pager-duty"]
        enable_spot_instances = true
        enable_committed_use_discounts = false
        tags = {
          environment = "production"
          project = "alpha-orion"
          component = "arbitrage"
          managed-by = "terraform"
          build-id = "$BUILD_ID"
        }
        EOF

        echo "âœ… Terraform initialized with enterprise configuration"
    waitFor: ['build-frontend', 'build-backend']

  - name: 'hashicorp/terraform:1.5.0'
    id: 'terraform-plan'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "ðŸ“‹ Creating Terraform deployment plan"
        cd infrastructure

        # Create execution plan
        terraform plan -out=tfplan -var-file=terraform.tfvars

        # Show plan summary
        echo "ðŸ“Š Terraform Plan Summary:"
        terraform show -no-color tfplan | tail -20
    waitFor: ['terraform-init']

  - name: 'hashicorp/terraform:1.5.0'
    id: 'terraform-apply'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "ðŸš€ Deploying Enterprise Infrastructure"
        cd infrastructure

        # Apply infrastructure changes
        terraform apply -auto-approve -var-file=terraform.tfvars

        # Get outputs for next steps
        terraform output -json > ../terraform-outputs.json

        echo "âœ… Enterprise infrastructure deployed successfully"
    waitFor: ['terraform-plan']

  # Step 5: Deploy Cloud Run services
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-cloud-run'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "ðŸš€ Deploying Cloud Run Services"

        # Deploy user API service
        gcloud run deploy alpha-orion-user-api \
          --image gcr.io/$PROJECT_ID/alpha-orion-user-api:$COMMIT_SHA \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated \
          --memory 2Gi \
          --cpu 2 \
          --max-instances 10 \
          --min-instances 1 \
          --port 8080 \
          --set-env-vars "NODE_ENV=production,PROJECT_ID=$PROJECT_ID" \
          --project=$PROJECT_ID

        # Deploy AI agent service
        gcloud run deploy alpha-orion-ai-agent \
          --image gcr.io/$PROJECT_ID/alpha-orion-ai-agent:$COMMIT_SHA \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated \
          --memory 4Gi \
          --cpu 2 \
          --max-instances 5 \
          --min-instances 1 \
          --port 8080 \
          --set-env-vars "NODE_ENV=production,PROJECT_ID=$PROJECT_ID" \
          --project=$PROJECT_ID

        # Deploy brain orchestrator
        gcloud run deploy alpha-orion-brain \
          --image gcr.io/$PROJECT_ID/alpha-orion-brain:$COMMIT_SHA \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated \
          --memory 8Gi \
          --cpu 4 \
          --max-instances 3 \
          --min-instances 1 \
          --port 8080 \
          --set-env-vars "NODE_ENV=production,PROJECT_ID=$PROJECT_ID" \
          --project=$PROJECT_ID

        echo "âœ… Cloud Run services deployed"
    waitFor: ['terraform-apply']

  # Step 6: Configure monitoring and alerting
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'setup-monitoring'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "ðŸ“Š Setting up Enterprise Monitoring & Alerting"

        # Create custom metrics
        gcloud monitoring metrics create arbitrage/profit_rate \
          --description="Arbitrage profit generation rate" \
          --unit="USD/min" \
          --metric-kind=GAUGE \
          --value-type=DOUBLE \
          --project=$PROJECT_ID

        gcloud monitoring metrics create arbitrage/execution_latency \
          --description="Trade execution latency" \
          --unit="ms" \
          --metric-kind=GAUGE \
          --value-type=DOUBLE \
          --project=$PROJECT_ID

        gcloud monitoring metrics create arbitrage/success_rate \
          --description="Trade success rate" \
          --unit="%" \
          --metric-kind=GAUGE \
          --value-type=DOUBLE \
          --project=$PROJECT_ID

        # Create notification channels
        gcloud monitoring channels create email-channel \
          --display-name="Alpha-Orion Alerts" \
          --type=email \
          --channel-labels=email_address=alerts@alpha-orion.com \
          --project=$PROJECT_ID

        # Create alerting policies
        gcloud monitoring policies create latency-alert \
          --display-name="High Execution Latency" \
          --condition-filter="metric.type=\"custom.googleapis.com/arbitrage/execution_latency\" AND resource.type=\"global\"" \
          --condition-threshold=50 \
          --condition-comparison=COMPARISON_GT \
          --notification-channels=email-channel \
          --project=$PROJECT_ID

        echo "âœ… Enterprise monitoring configured"
    waitFor: ['deploy-cloud-run']

  # Step 7: Run post-deployment tests
  - name: 'python:3.9'
    id: 'post-deployment-tests'
    entrypoint: 'python3'
    args:
      - 'gcp-infrastructure-verification.py'
      - '--project=$PROJECT_ID'
    waitFor: ['setup-monitoring']

  # Step 8: Update deployment status
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'update-deployment-status'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "ðŸ“‹ Updating deployment status"

        # Create deployment record
        cat > deployment-status.json << EOF
        {
          "deployment_id": "$BUILD_ID",
          "commit_sha": "$COMMIT_SHA",
          "branch": "$BRANCH_NAME",
          "timestamp": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
          "project_id": "$PROJECT_ID",
          "status": "SUCCESS",
          "infrastructure": {
            "compute_engine": "Deployed",
            "bigtable": "Deployed",
            "dataflow": "Deployed",
            "vertex_ai": "Deployed",
            "cloud_run": "Deployed",
            "load_balancer": "Deployed",
            "monitoring": "Configured"
          },
          "services": {
            "frontend": "gcr.io/$PROJECT_ID/alpha-orion-frontend:$COMMIT_SHA",
            "user_api": "gcr.io/$PROJECT_ID/alpha-orion-user-api:$COMMIT_SHA",
            "ai_agent": "gcr.io/$PROJECT_ID/alpha-orion-ai-agent:$COMMIT_SHA",
            "brain_orchestrator": "gcr.io/$PROJECT_ID/alpha-orion-brain:$COMMIT_SHA"
          },
          "performance_targets": {
            "latency": "< 50ms",
            "throughput": "> 1000 ops/sec",
            "uptime": "99.9%",
            "accuracy": "> 95%"
          }
        }
        EOF

        # Upload status to Cloud Storage
        gsutil cp deployment-status.json gs://$PROJECT_ID-deployments/status/$BUILD_ID.json

        echo "âœ… Deployment status updated"
    waitFor: ['post-deployment-tests']

# Build configuration
timeout: '3600s'
machineType: 'E2_HIGHCPU_8'

# Secrets
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/gcp-service-account-key/versions/latest
    env: GCP_SERVICE_ACCOUNT_KEY

# Environment variables
env:
  - 'PROJECT_ID=$PROJECT_ID'
  - 'BRANCH_NAME=$BRANCH_NAME'
  - 'COMMIT_SHA=$COMMIT_SHA'
  - 'BUILD_ID=$BUILD_ID'

# Artifacts
artifacts:
  objects:
    location: 'gs://$PROJECT_ID-deployments/artifacts/$BUILD_ID/'
    paths:
      - 'terraform-outputs.json'
      - 'gcp-deployment-fix-report.json'
      - 'gcp-verification-results.json'
      - 'deployment-status.json'

# Options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100
  substitutionOption: ALLOW_LOOSE
  dynamicSubstitutions: true

# Triggers (configured separately)
# trigger:
#   branch: main
#   includedFiles:
#     - '**/*'
#   ignoredFiles:
#     - 'README.md'
#     - 'docs/**'
#     - '*.md'