steps:
  # ==============================================================================
  # 1. USER API SERVICE
  # ==============================================================================
  
  # Build User API
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'backend-services/services/user-api-service'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/user-api-service', '.']

  # Push User API
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/user-api-service']

  # Deploy User API
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'user-api-service'
      - '--image'
      - 'gcr.io/$PROJECT_ID/user-api-service'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'NODE_ENV=production,GCP_PROJECT_ID=$PROJECT_ID,MIN_PROFIT_THRESHOLD_USD=500,AUTO_WITHDRAWAL_THRESHOLD_USD=1000'

  # ==============================================================================
  # 2. AI OPTIMIZER SERVICE
  # ==============================================================================

  # Build AI Optimizer
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'backend-services/services/ai-optimizer'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/brain-ai-optimizer-us', '.']

  # Push AI Optimizer
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/brain-ai-optimizer-us']

  # Deploy AI Optimizer
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'brain-ai-optimizer-us', '--image', 'gcr.io/$PROJECT_ID/brain-ai-optimizer-us', '--region', 'us-central1', '--allow-unauthenticated', '--set-env-vars', 'NODE_ENV=production,GCP_PROJECT_ID=$PROJECT_ID']

  # ==============================================================================
  # 3. FRONTEND DASHBOARD SERVICE
  # ==============================================================================

  # Build Frontend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/frontend-dashboard', '.']

  # Push Frontend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/frontend-dashboard']

  # Deploy Frontend
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'frontend-dashboard', '--image', 'gcr.io/$PROJECT_ID/frontend-dashboard', '--region', 'us-central1', '--allow-unauthenticated']

images:
  - 'gcr.io/$PROJECT_ID/user-api-service'
  - 'gcr.io/$PROJECT_ID/brain-ai-optimizer-us'
  - 'gcr.io/$PROJECT_ID/frontend-dashboard'