# Alpha-Orion Production Cloud Build Configuration
# This file containerizes and deploys all core services to Google Cloud Run.
# It incorporates fixes from the deployment analysis, including secret management.

options:
  machineType: 'E2_HIGHCPU_8'
  substitutionOption: 'ALLOW_LOOSE'
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: 'us-central1'
  # CRITICAL FIX: Replace with actual production API URL after first deployment
  # Use Cloud Load Balancer or API Gateway URL for production
  _API_URL: '${_REGION}-run.googleapis.com'

steps:
  # ==============================================================================
  # 1. USER API SERVICE (Node.js - Main API)
  # ==============================================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-user-api'
    dir: 'backend-services/services/user-api-service/src'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/user-api-service:$COMMIT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/user-api-service:$COMMIT_SHA']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-user-api'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'user-api-service'
      - '--image'
      - 'gcr.io/$PROJECT_ID/user-api-service:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      # CRITICAL SECURITY FIX: Remove unauthenticated access
      # Use IAM authentication and internal-only traffic
      - '--ingress'
      - 'internal'
      - '--no-allow-unauthenticated'
      - '--memory=2Gi'
      - '--cpu=2'
      - '--min-instances=1'
      - '--max-instances=10'
      - '--timeout=3600s'
      - '--concurrency=80'
      - '--set-env-vars=PORT=8080,NODE_ENV=production,GCP_PROJECT_ID=$PROJECT_ID'
      - >-
        --set-secrets=DATABASE_URL=DATABASE_URL:latest,REDIS_URL=REDIS_URL:latest,JWT_SECRET_KEY=JWT_SECRET_KEY:latest,PIMLICO_API_KEY=PIMLICO_API_KEY:latest,GEMINI_API_KEY=GEMINI_API_KEY:latest,ETHEREUM_RPC_URL=ETHEREUM_RPC_URL:latest,PROFIT_WALLET_ADDRESS=PROFIT_WALLET_ADDRESS:latest

  # ==============================================================================
  # 2. FRONTEND DASHBOARD (Nginx to serve static files)
  # ==============================================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-frontend'
    dir: '.' # Build from root
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/frontend-dashboard:$COMMIT_SHA', '-f', 'docker/frontend.Dockerfile', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/frontend-dashboard:$COMMIT_SHA']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-frontend'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'frontend-dashboard' # Correct service name
      - '--image'
      - 'gcr.io/$PROJECT_ID/frontend-dashboard:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--port=80' # Nginx listens on port 80
      - '--set-env-vars=API_BASE_URL=${_API_URL}' # For Nginx proxy or runtime injection

  # ==============================================================================
  # 3. BRAIN ORCHESTRATOR (Python - Tier 1)
  # ==============================================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-brain-orchestrator'
    dir: 'backend-services/services/brain-orchestrator'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/brain-orchestrator:$COMMIT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/brain-orchestrator:$COMMIT_SHA']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-brain-orchestrator'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'brain-orchestrator'
      - '--image'
      - 'gcr.io/$PROJECT_ID/brain-orchestrator:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--no-allow-unauthenticated' # Internal service
      - '--memory=1Gi'
      - '--cpu=2'
      - '--min-instances=1'
      - '--max-instances=5'
      - '--timeout=3600s'
      - '--set-env-vars=PYTHONUNBUFFERED=1,GCP_PROJECT_ID=$PROJECT_ID'

  # ==============================================================================
  # 4. BRAIN AI OPTIMIZATION ORCHESTRATOR (Python - Tier 2)
  # ==============================================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-brain-ai-optimizer'
    dir: 'backend-services/services/brain-ai-optimization-orchestrator'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/brain-ai-optimizer:$COMMIT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/brain-ai-optimizer:$COMMIT_SHA']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-brain-ai-optimizer'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'brain-ai-optimizer'
      - '--image'
      - 'gcr.io/$PROJECT_ID/brain-ai-optimizer:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--no-allow-unauthenticated' # Internal service
      - '--memory=2Gi'
      - '--cpu=2'
      - '--min-instances=1'
      - '--max-instances=5'
      - '--set-env-vars=PYTHONUNBUFFERED=1,GCP_PROJECT_ID=$PROJECT_ID'

  # ==============================================================================
  # 5. BLOCKCHAIN MONITOR (Python - Tier 2)
  # ==============================================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-blockchain-monitor'
    dir: 'backend-services/services/blockchain-monitor'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/blockchain-monitor:$COMMIT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/blockchain-monitor:$COMMIT_SHA']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-blockchain-monitor'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'blockchain-monitor'
      - '--image'
      - 'gcr.io/$PROJECT_ID/blockchain-monitor:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--no-allow-unauthenticated' # Internal service
      - '--memory=512Mi'
      - '--cpu=1'
      - '--set-env-vars=PYTHONUNBUFFERED=1,GCP_PROJECT_ID=$PROJECT_ID'

  # ==============================================================================
  # 6. COMPLIANCE SERVICE (Python - Tier 2)
  # ==============================================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-compliance-service'
    dir: 'backend-services/services/compliance-service'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/compliance-service:$COMMIT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/compliance-service:$COMMIT_SHA']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-compliance-service'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'compliance-service'
      - '--image'
      - 'gcr.io/$PROJECT_ID/compliance-service:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--no-allow-unauthenticated' # Internal service
      - '--memory=512Mi'
      - '--cpu=1'
      - '--set-env-vars=PYTHONUNBUFFERED=1,GCP_PROJECT_ID=$PROJECT_ID'

  # ==============================================================================
  # 7. SMART CONTRACT MONITOR (Python - Tier 3)
  # ==============================================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-smart-contract-monitor'
    dir: 'backend-services/services/smart-contract-monitor'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/smart-contract-monitor:$COMMIT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/smart-contract-monitor:$COMMIT_SHA']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-smart-contract-monitor'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'smart-contract-monitor'
      - '--image'
      - 'gcr.io/$PROJECT_ID/smart-contract-monitor:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--no-allow-unauthenticated' # Internal service
      - '--memory=512Mi'
      - '--cpu=1'
      - '--set-env-vars=PYTHONUNBUFFERED=1,GCP_PROJECT_ID=$PROJECT_ID'

  # ==============================================================================
  # 8. FINANCIAL RECONCILIATION (Python - Tier 3)
  # ==============================================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-financial-reconciliation'
    dir: 'backend-services/services/financial-reconciliation'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/financial-reconciliation:$COMMIT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/financial-reconciliation:$COMMIT_SHA']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-financial-reconciliation'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'financial-reconciliation'
      - '--image'
      - 'gcr.io/$PROJECT_ID/financial-reconciliation:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--no-allow-unauthenticated' # Internal service
      - '--memory=512Mi'
      - '--cpu=1'
      - '--set-env-vars=PYTHONUNBUFFERED=1,GCP_PROJECT_ID=$PROJECT_ID'

# List of images to be built and pushed.
images:
  - 'gcr.io/$PROJECT_ID/user-api-service:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/frontend-dashboard:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/brain-orchestrator:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/brain-ai-optimizer:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/blockchain-monitor:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/compliance-service:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/smart-contract-monitor:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/financial-reconciliation:$COMMIT_SHA'
