
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.

provider "google" {
  project     = "alpha-orion-485207"
  region      = "us-east4"
  default_labels = {
    goog-adc-tf-deployment = "export"
  }
  billing_project       = "alpha-orion"
  user_project_override = true
}
provider "google-beta" {
  default_labels = {
    goog-adc-tf-deployment = "export"
  }
  billing_project       = "alpha-orion"
  user_project_override = true
}
