services:
  - type: web
    name: alpha-orion-backend
    env: node
    root: backend-services/services/user-api-service
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22.16.0