#!/usr/bin/env python3
"""
Profit Stream Verification Script
Chief Architect's tool to verify the live data feed from the arbitrage engine.
"""

import subprocess
import sys

try:
    import requests
except ImportError:
    print("Installing required package: requests...")
    subprocess.check_call([sys.executable, "-m", "pip", "install", "requests"])
    import requests

import os
import json
import time

class Colors:
    HEADER = '\033[95m'
    BLUE = '\033[94m'
    GREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'

def get_project_id():
    """Get the active GCP project ID"""
    project_id = os.environ.get("GCP_PROJECT_ID")
    if project_id:
        return project_id
    
    script_dir = os.path.dirname(os.path.abspath(__file__))
    paths = [os.path.join(os.getcwd(), '.env'), os.path.join(script_dir, '.env')]
    for env_path in paths:
        if os.path.exists(env_path):
            try:
                with open(env_path, "r") as f:
                    for line in f:
                        if line.startswith("GCP_PROJECT_ID="):
                            return line.split("=")[1].strip().strip('"').strip("'")
            except:
                pass
    return "alpha-orion-485207"

def get_cloud_run_url(project_id, service_name="user-api-service"):
    """Get the URL for a Cloud Run service"""
    try:
        cmd = [
            "gcloud", "run", "services", "describe", service_name,
            f"--project={project_id}",
            "--platform=managed",
            "--region=us-central1",
            "--format=value(status.url)"
        ]
        result = subprocess.run(cmd, capture_output=True, text=True, encoding='utf-8', errors='replace')
        if result.returncode == 0 and result.stdout.strip():
            return result.stdout.strip()
    except:
        pass
    return None

def get_dashboard_url():
    """Retrieve the running dashboard URL"""
    port = 8888
    # Try to read from the port file generated by serve-live-dashboard.py
    if os.path.exists('dashboard_port.txt'):
        try:
            with open('dashboard_port.txt', 'r') as f:
                content = f.read().strip()
                if content.isdigit():
                    port = int(content)
        except:
            pass
    
    # Fallback to checking environment or default
    return f"http://localhost:{port}"

def verify_endpoint(base_url, endpoint, description):
    print(f"{description} ({endpoint})...", end=" ")
    try:
        resp = requests.get(f"{base_url}{endpoint}", timeout=5)
        if resp.status_code == 200:
            print(f"{Colors.GREEN}✅ ACTIVE{Colors.ENDC}")
            return True, resp.json() if resp.content else {}
        else:
            print(f"{Colors.FAIL}❌ ERROR ({resp.status_code}){Colors.ENDC}")
            return False, None
    except Exception as e:
        print(f"{Colors.FAIL}❌ FAILED ({e}){Colors.ENDC}")
        return False, None

def verify_stream():
    print(f"{Colors.BOLD}{Colors.HEADER}ALPHA-ORION PROFIT STREAM VERIFICATION{Colors.ENDC}")
    print("=" * 60)
    
    base_url = get_dashboard_url()
    print(f"Target Dashboard: {Colors.BLUE}{base_url}{Colors.ENDC}")
    
    # 1. Check Dashboard Connectivity
    dashboard_ok = False
    try:
        resp = requests.get(base_url, timeout=2)
        if resp.status_code == 200:
            print(f"1. Dashboard Connectivity... {Colors.GREEN}✅ ONLINE{Colors.ENDC}")
            dashboard_ok = True
        else:
            print(f"1. Dashboard Connectivity... {Colors.FAIL}❌ ERROR ({resp.status_code}){Colors.ENDC}")
    except Exception as e:
        print(f"1. Dashboard Connectivity... {Colors.FAIL}❌ UNREACHABLE{Colors.ENDC}")

    # 2. Check Trades Endpoint (The Stream)
    stream_ok, data = verify_endpoint(base_url, "/trades/executed", "2. Verifying Trades Stream")

    # 3. Check PnL Endpoint
    pnl_ok, pnl_data = verify_endpoint(base_url, "/analytics/total-pnl", "3. Verifying PnL Analytics")

    # 4. Cloud Fallback if Local Failed
    if not stream_ok or not pnl_ok:
        print("\n" + "-" * 60)
        print(f"{Colors.WARNING}⚠️  Local proxy failed. Attempting direct Cloud Run verification...{Colors.ENDC}")
        
        project_id = get_project_id()
        print(f"   Project ID: {project_id}")
        cloud_url = get_cloud_run_url(project_id)
        
        if cloud_url:
            print(f"   Cloud URL:  {Colors.BLUE}{cloud_url}{Colors.ENDC}")
            
            c_stream_ok, c_data = verify_endpoint(cloud_url, "/trades/executed", "   ☁️  Cloud Trades Stream")
            c_pnl_ok, c_pnl_data = verify_endpoint(cloud_url, "/analytics/total-pnl", "   ☁️  Cloud PnL Analytics")
            
            if c_stream_ok and c_pnl_ok:
                print(f"\n{Colors.GREEN}✅ CLOUD DEPLOYMENT IS HEALTHY!{Colors.ENDC}")
                print(f"   The issue is your local dashboard configuration.")
                print(f"   👉 Run this to fix: {Colors.BOLD}set BACKEND_URL={cloud_url} && python serve-live-dashboard.py{Colors.ENDC}")
            else:
                print(f"\n{Colors.FAIL}❌ CLOUD DEPLOYMENT UNHEALTHY{Colors.ENDC}")
        else:
            print(f"{Colors.FAIL}❌ Could not retrieve Cloud Run URL.{Colors.ENDC}")

    print("\n" + "=" * 60)
    if (stream_ok and pnl_ok) or (locals().get('c_stream_ok') and locals().get('c_pnl_ok')):
        print(f"{Colors.GREEN}Verification Complete: SYSTEM OPERATIONAL{Colors.ENDC}")
    else:
        print(f"{Colors.FAIL}Verification Complete: SYSTEM ISSUES DETECTED{Colors.ENDC}")

if __name__ == "__main__":
    verify_stream()