apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: alpha-orion-brain-orchestrator-hpa
  namespace: alpha-orion
  labels:
    app: brain-ai-optimization-orchestrator
    component: arbitrage-engine
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: brain-ai-optimization-orchestrator
  minReplicas: 3
  maxReplicas: 50
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  - type: Pods
    pods:
      metric:
        name: arbitrage_opportunities_per_second
      target:
        type: AverageValue
        averageValue: 100
  - type: Pods
    pods:
      metric:
        name: active_arbitrage_positions
      target:
        type: AverageValue
        averageValue: 25
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 20
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 5
        periodSeconds: 60
      selectPolicy: Max
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: alpha-orion-dashboard-hpa
  namespace: alpha-orion
  labels:
    app: alpha-orion-dashboard
    component: frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: alpha-orion-dashboard
  minReplicas: 2
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 600
      policies:
      - type: Percent
        value: 30
        periodSeconds: 120
    scaleUp:
      stabilizationWindowSeconds: 120
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: alpha-orion-risk-engine-hpa
  namespace: alpha-orion
  labels:
    app: risk-engine
    component: risk-management
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: risk-engine
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 65
  - type: Pods
    pods:
      metric:
        name: risk_calculations_per_second
      target:
        type: AverageValue
        averageValue: 50
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 900
      policies:
      - type: Percent
        value: 25
        periodSeconds: 180
    scaleUp:
      stabilizationWindowSeconds: 180
      policies:
      - type: Percent
        value: 75
        periodSeconds: 120
